### PR TITLE
WIP: Refactor to enable error handling

### PR DESCRIPTION
**Pull request by vikin91**
This PR refactors the code to enable bubbling up the errors based on a setting.

Do not merge: not finished yet!

### CODE REVIEW

**Comment by zivnevo** [comment]
Thanks @vikin91 for this work. Hopefully I now better understand the motivation.
Once you feel the code is ready and all tests pass, please assign me as the reviewer and I will add my comments with code context.
Two general comments:
* This PR seems to handle several issues together: improve error handling, improve yaml scanning and general refactoring. When possible, please prefer multiple small and focused PRs over one multi-issue PR.
* Please follow existing style, unless there is a good reason not to. E.g., avoid changing `links := []common.Service{}` to `links := make([]common.Service, 0)`.

**Comment by vikin91** [comment]
@zivnevo based on our recent discussions, would it be okay to close this PR? I can keep the fork alive for some time in case we would like to salvage some parts out of it.

**Comment by zivnevo** [comment]
yes, it's ok to close this PR. please keep the fork alive until the release, just in case I'll want to take a peek

**Comment by vikin91** [comment]
Closing as discussed.

**Pull request closed without merging**
